---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-ui
  labels:
    name: kanban-ui
  namespace: my-kanban
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kanban-ui
  template:
    metadata:
      labels:
        name: kanban-ui
    spec:
      containers:
      - name: kanban-ui
        # github: https://github.com/amnay-mo/kanban-ui
        image: eu.gcr.io/myfoobarproject/kanban-ui:0.6
        ports:
        - containerPort: 80
